"""modelos iniciais

Revision ID: 8ff1f0a0d654
Revises: 
Create Date: 2026-08-15 15:10:20.274560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff1f0a0d654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k_anonimato_threshold', sa.Integer(), nullable=False),
    sa.Column('ia_sugestao_questionario_enabled', sa.Boolean(), nullable=False),
    sa.Column('ia_analise_resultados_enabled', sa.Boolean(), nullable=False),
    sa.Column('ia_chat_enabled', sa.Boolean(), nullable=False),
    sa.Column('llm_provider', sa.String(length=30), nullable=True),
    sa.Column('llm_api_key', sa.String(length=255), nullable=True),
    sa.Column('llm_base_url', sa.String(length=255), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instituicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('instrumento', sa.String(length=50), nullable=False),
    sa.Column('versao', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dominios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dominios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dominios_questionario_id'), ['questionario_id'], unique=False)

    op.create_table('setores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setores_instituicao_id'), ['instituicao_id'], unique=False)

    op.create_table('itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dominio_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('tipo_resposta', sa.String(length=30), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('escala_min', sa.Integer(), nullable=False),
    sa.Column('escala_max', sa.Integer(), nullable=False),
    sa.Column('invertido', sa.Boolean(), nullable=False),
    sa.Column('regra_condicional', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dominio_id'], ['dominios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_dominio_id'), ['dominio_id'], unique=False)

    op.create_table('respostas_brutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('respondido_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionarios.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('respostas_brutas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_respostas_brutas_instituicao_id'), ['instituicao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_respostas_brutas_questionario_id'), ['questionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_respostas_brutas_setor_id'), ['setor_id'], unique=False)

    op.create_table('resultados_agregados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.Column('dominio_id', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.String(length=30), nullable=False),
    sa.Column('valor_agregado', sa.JSON(), nullable=True),
    sa.Column('n_respostas', sa.Integer(), nullable=False),
    sa.Column('calculado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dominio_id'], ['dominios.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionarios.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resultados_agregados', schema=None) as batch_op:
        batch_op.create_index('ix_resultados_agregados_grupo', ['instituicao_id', 'setor_id', 'questionario_id', 'dominio_id', 'periodo'], unique=False)
        batch_op.create_index(batch_op.f('ix_resultados_agregados_instituicao_id'), ['instituicao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resultados_agregados_questionario_id'), ['questionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resultados_agregados_setor_id'), ['setor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados_agregados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resultados_agregados_setor_id'))
        batch_op.drop_index(batch_op.f('ix_resultados_agregados_questionario_id'))
        batch_op.drop_index(batch_op.f('ix_resultados_agregados_instituicao_id'))
        batch_op.drop_index('ix_resultados_agregados_grupo')

    op.drop_table('resultados_agregados')
    with op.batch_alter_table('respostas_brutas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_respostas_brutas_setor_id'))
        batch_op.drop_index(batch_op.f('ix_respostas_brutas_questionario_id'))
        batch_op.drop_index(batch_op.f('ix_respostas_brutas_instituicao_id'))

    op.drop_table('respostas_brutas')
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_dominio_id'))

    op.drop_table('itens')
    with op.batch_alter_table('setores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setores_instituicao_id'))

    op.drop_table('setores')
    with op.batch_alter_table('dominios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dominios_questionario_id'))

    op.drop_table('dominios')
    op.drop_table('questionarios')
    op.drop_table('instituicoes')
    op.drop_table('configuracoes_sistema')
    # ### end Alembic commands ###


def upgrade_auth():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('consultor_instituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'instituicao_id', name='uq_consultor_instituicao')
    )
    with op.batch_alter_table('consultor_instituicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultor_instituicao_instituicao_id'), ['instituicao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultor_instituicao_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('log_atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('entidade', sa.String(length=100), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_atividade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_atividade_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_atividade_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('sessao_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessao_login', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessao_login_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessao_login_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade_auth():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessao_login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessao_login_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_sessao_login_token'))

    op.drop_table('sessao_login')
    with op.batch_alter_table('log_atividade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_atividade_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_log_atividade_criado_em'))

    op.drop_table('log_atividade')
    with op.batch_alter_table('consultor_instituicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultor_instituicao_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_consultor_instituicao_instituicao_id'))

    op.drop_table('consultor_instituicao')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###


def upgrade_memoria():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituicoes_referencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instituicoes_referencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instituicoes_referencia_instituicao_id'), ['instituicao_id'], unique=True)

    op.create_table('registros_memoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('anexo_url', sa.String(length=500), nullable=True),
    sa.Column('criado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_memoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_memoria_instituicao_id'), ['instituicao_id'], unique=False)

    op.create_table('linha_do_tempo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.String(length=255), nullable=False),
    sa.Column('data_evento', sa.Date(), nullable=False),
    sa.Column('registro_memoria_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['registro_memoria_id'], ['registros_memoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('linha_do_tempo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linha_do_tempo_instituicao_id'), ['instituicao_id'], unique=False)

    # ### end Alembic commands ###


def downgrade_memoria():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linha_do_tempo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linha_do_tempo_instituicao_id'))

    op.drop_table('linha_do_tempo')
    with op.batch_alter_table('registros_memoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_memoria_instituicao_id'))

    op.drop_table('registros_memoria')
    with op.batch_alter_table('instituicoes_referencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instituicoes_referencia_instituicao_id'))

    op.drop_table('instituicoes_referencia')
    # ### end Alembic commands ###

